### ISSUE TITLE
Input an empty file to the PD5M-resource

### ISSUE THREAD

**Issue by xSilvermanx** [xSilvermanx/PD5M#17]
This should be a file that allows for custom code to be executed. When installing an update you just need to remember not to overwrite said file.

**Comment by jackjordan12** [comment]
Maybe this could be packaged seperately (similar to how FiveM packages the server.cfg seperately)?

Another alternative would be to use convars in the server.cfg (though I personally hate these).

**Comment by xSilvermanx** [comment]
While thinking about this it shouldn't be necessary at all since you can just create the file yourself and enable it in the __resource.lua . Also if you do that it's clear that you'd need to readd it after an update but would not run the risk of accidentally deleting it. Thus -> closed, no change.
