### ISSUE TITLE
Introducing more user friendly controls for controller users

### ISSUE THREAD

**Issue by jackjordan12** [xSilvermanx/PD5M#19]
Thought I would throw this up here (after our discussion a couple of days ago).

Maybe introducing basic functions on radial menu where controller 'B' is used to pull up the radial menu (whilst in vehicle) and using the right analog stick to navigate through this menu?

**Comment by DrBlackError** [comment]
How do you drive, press 'B' and navigate with the right analog stick? O.o

**Comment by jackjordan12** [comment]
No

**Comment by xSilvermanx** [comment]
Done in next version.
