### ISSUE TITLE
Is PD5M overriding ped group relationships? 

### ISSUE THREAD

**Issue by jdalvarez23** [xSilvermanx/PD5M#53]
I have written some code for peds to attack players and it seems like it does not work when I have PD5M installed. I am using the SetPedRelationshipGroupHash() native and it seems to only work when I completely remove PD5M. Is there any way to turn that off without making PD5M break? And if so, would you be able to point to me where you are overriding ped relationships?

Thanks!

**Comment by xSilvermanx** [comment]
Two places to check:
a) `Startup/startup_cl.lua` - lines 4 and 6
b) `Interaction/pednopanic_cl.lua` - the whole script

Also I just have to advertise: If you join the PD5M-discord communicating with everyone (including me) will be way easier :D
Please respond to this issue so I can close it if deactivating the above lines / file worked.

**Comment by jdalvarez23** [comment]
It was the whole script in `Interaction/pednopanic_cl.lua`. That fixed the issue. Thank you so much for your help!
