### ISSUE TITLE
Breathalzier

### ISSUE THREAD

**Issue by frazz1234** [xSilvermanx/PD5M#57]
No Emote, no interaction with the ped and no nothing happen

**Comment by xSilvermanx** [comment]
did you tell the ped that you will have them take a breathalyzer?
Do the peds back off a bit?

**Comment by frazz1234** [comment]
Yes I try several time

**Comment by xSilvermanx** [comment]
https://www.youtube.com/watch?v=7P4I_Tjr9I4

This should explain how to use a breathalyzer. Please check if your problem persists and report back whether I can close this issue.
